### PR TITLE
Fixed package resolving during indexing process. 

### LINKED ISSUE #831: Interface Implementations not being found 2018
Go to implementations results in "No Implementations found" message.
The clickable gutter icon showing that an interface is implemented is missing. 

Was working in 2017, hasn't been in the 2018 versions I've used.

### PR DESCRIPTION
**Pull request by mayakwd**
Closes #831

### CODE REVIEW

File: src/common/com/intellij/plugins/haxe/model/HaxeSourceRootModel.java [hunk 1]
```diff
@@ -50,6 +51,9 @@ public boolean contains(PsiFileSystemItem file) {
     if (virtualFile == null) {
       virtualFile = file.getOriginalElement().getContainingFile().getVirtualFile();
     }
+    if (virtualFile == null) {
+      virtualFile = file.getUserData(IndexingDataKeys.VIRTUAL_FILE);
```
Comment (EricBishton) [inline src/common/com/intellij/plugins/haxe/model/HaxeSourceRootModel.java]: Well, hell.  What a workaround.  But since JetBrains does this for their own indexing, it must be a valid way to go about it.  Good job finding that.

Comment (mayakwd) [reply src/common/com/intellij/plugins/haxe/model/HaxeSourceRootModel.java]: I've spent two days in deep debugging to write this three lines 😅

Comment (EricBishton) [reply src/common/com/intellij/plugins/haxe/model/HaxeSourceRootModel.java]: Some days it goes like that...  It's good to get the problem fixed, though.
