### PR TITLE
Fix resolving through abstracts using generic underlying types.

### LINKED ISSUE #772: Autocomplete does not work for List elements and abstract classes
```
var list:List<Something> = new List();

for(element in list) {
    element. //no code tips here
}
```
This does not work, because the List.iterator() method returns a exemplar ListIterator<T>. If I change it to an Iterator<T>, then the autocomplete starts working.

```
@:forward
abstract AbstractWrapper<T>(T) from T to T {
    public inline function new(value:T) this = value;
}

var obj:AbstractWrapper<Something> = new Something();
obj. //no code tips here
```

These problems are not present if you enable the checkbox Use compiler in the SDK settings.

### PR DESCRIPTION
**Pull request by EricBishton**
I.e. abstract MyClass<T>(T){}
Fixes #772

### CODE REVIEW

File: src/common/com/intellij/plugins/haxe/model/HaxeAbstractClassModel.java [hunk 1]
```diff
@@ -57,24 +57,32 @@ public HaxeClass getUnderlyingClass(@Nullable final HaxeGenericResolver resolver
...
     }
     HaxeTypeOrAnonymous anonymous = underlyingTypePsi.getTypeOrAnonymous();
     final HaxeType underlyingType = anonymous != null ? anonymous.getType() : null;
     if (underlyingType != null) {
-      final HaxeClassResolveResult result = underlyingType.getReferenceExpression().resolveHaxeClass();
-      return result.getHaxeClass();
+      HaxeReferenceExpression referenceExpression = underlyingType.getReferenceExpression();
+      final HaxeClassResolveResult result = referenceExpression.resolveHaxeClass();
+      HaxeClass resultClass = result.getHaxeClass();
+      return null != resultClass ? resultClass : resolveGeneric(referenceExpression.getIdentifier().getText(), resolver);
```
Comment (EricBishton) [inline src/common/com/intellij/plugins/haxe/model/HaxeAbstractClassModel.java]: Simple fix.  If we weren't able to resolve the underlying class, check against the generic specialization/resolver.
